site_name: Workout Project
site_url: https://1880160.github.io/Projet_workout_wiki

theme:
  name: material
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: es
          name: Español
          build: true